# Generated by Django 3.1.1 on 2020-09-23 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['game', 'name']},
        ),
        migrations.AlterModelOptions(
            name='matchtype',
            options={'ordering': ['level', 'mode']},
        ),
        migrations.AlterModelOptions(
            name='mode',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_game'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_level'),
        ),
        migrations.AddConstraint(
            model_name='matchtype',
            constraint=models.UniqueConstraint(fields=('level', 'mode'), name='unique_match_type'),
        ),
        migrations.AddConstraint(
            model_name='mode',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_mode'),
        ),
    ]
